//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaoCoopApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ViewModelStringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewModelStringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NaoCoopApp.Resources.ViewModelStringResources", typeof(ViewModelStringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7_Nao_copy {
            get {
                object obj = ResourceManager.GetObject("_7_Nao_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executions description..
        /// </summary>
        internal static string ExecutionsViewModel_Description {
            get {
                return ResourceManager.GetString("ExecutionsViewModel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executions.
        /// </summary>
        internal static string ExecutionsViewModel_Title {
            get {
                return ResourceManager.GetString("ExecutionsViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations description..
        /// </summary>
        internal static string OperationsViewModel_Description {
            get {
                return ResourceManager.GetString("OperationsViewModel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        internal static string OperationsViewModel_Title {
            get {
                return ResourceManager.GetString("OperationsViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirements description..
        /// </summary>
        internal static string RequirementsViewModel_Description {
            get {
                return ResourceManager.GetString("RequirementsViewModel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirements.
        /// </summary>
        internal static string RequirementsViewModel_Title {
            get {
                return ResourceManager.GetString("RequirementsViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robots description..
        /// </summary>
        internal static string RobotsViewModel_Description {
            get {
                return ResourceManager.GetString("RobotsViewModel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robots.
        /// </summary>
        internal static string RobotsViewModel_Title {
            get {
                return ResourceManager.GetString("RobotsViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robot versions description..
        /// </summary>
        internal static string RobotVersionsViewModel_Description {
            get {
                return ResourceManager.GetString("RobotVersionsViewModel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robot Versions.
        /// </summary>
        internal static string RobotVersionsViewModel_Title {
            get {
                return ResourceManager.GetString("RobotVersionsViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to States description..
        /// </summary>
        internal static string StatesViewModel_Description {
            get {
                return ResourceManager.GetString("StatesViewModel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to States.
        /// </summary>
        internal static string StatesViewModel_Title {
            get {
                return ResourceManager.GetString("StatesViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks description..
        /// </summary>
        internal static string TasksViewModel_Description {
            get {
                return ResourceManager.GetString("TasksViewModel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        internal static string TasksViewModel_Title {
            get {
                return ResourceManager.GetString("TasksViewModel_Title", resourceCulture);
            }
        }
    }
}
